/*
 * File: app/view/AppViewPort.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StunningOctoPancake.view.AppViewPort', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.appviewport',

    requires: [
        'StunningOctoPancake.view.AppViewPortViewModel',
        'StunningOctoPancake.view.HeaderPanel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.File'
    ],

    viewModel: {
        type: 'appviewport'
    },
    style: 'background: #fff',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'headerpanel',
            flex: 1,
            margins: 'auto'
        },
        {
            xtype: 'tabpanel',
            flex: 1,
            frame: true,
            margin: '48 0 32',
            maxHeight: 310,
            maxWidth: 832.5,
            minWidth: 382.5,
            width: '75%',
            bodyBorder: false,
            bodyPadding: '64 32',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: 'Upload File',
                    layout: {
                        type: 'hbox',
                        align: 'middle'
                    },
                    items: [
                        {
                            xtype: 'filefield',
                            maxWidth: 680,
                            width: '100%',
                            fieldLabel: 'Choose CSV File:',
                            labelWidth: 110
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: '0 0 0 10',
                            text: 'Submit'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Search Imports',
                    layout: {
                        type: 'hbox',
                        align: 'middle'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            maxWidth: 680,
                            width: '100%',
                            fieldLabel: 'Search By Import Name',
                            labelWidth: 150
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: '0 0 0 10',
                            text: 'Search'
                        }
                    ]
                }
            ]
        }
    ]

});