/*
 * File: app/view/AppViewPort.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StunningOctoPancake.view.AppViewPort', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.appviewport',

    requires: [
        'StunningOctoPancake.view.AppViewPortViewModel',
        'StunningOctoPancake.view.HeaderPanel',
        'StunningOctoPancake.view.MyTabPanel',
        'Ext.tab.Panel'
    ],

    viewModel: {
        type: 'appviewport'
    },
    style: 'background: #fff',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'headerpanel',
            flex: 1,
            margins: 'auto'
        },
        {
            xtype: 'mytabpanel',
            flex: 1
        }
    ]

});