/*
 * File: app/view/MainContainer.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StunningOctoPancake.view.MainContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.maincontainer',

    requires: [
        'StunningOctoPancake.view.MainContainerViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.TextItem'
    ],

    viewModel: {
        type: 'maincontainer'
    },

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'toolbar',
            height: 72,
            style: 'background-color:#343a40',
            width: 832,
            items: [
                {
                    xtype: 'tbtext',
                    html: '<p style="font-size: 1.25rem; color: white">Stunning Octo Pancake</p>'
                }
            ]
        }
    ]

});