/*
 * File: app/view/RecordViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StunningOctoPancake.view.RecordViewport', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.recordviewport',

    requires: [
        'StunningOctoPancake.view.RecordViewportViewModel',
        'StunningOctoPancake.view.HeaderPanel',
        'Ext.Img',
        'Ext.button.Segmented',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'recordviewport'
    },

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'headerpanel',
            flex: 1,
            margins: 'auto'
        },
        {
            xtype: 'image',
            flex: 1,
            margin: 30,
            maxHeight: 300,
            minHeight: 300,
            width: 600,
            alt: 'Google Maps',
            src: 'https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=13&size=600x300&maptype=roadmap &markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:green%7Clabel:G%7C40.711614,-74.012318 &markers=color:red%7Clabel:C%7C40.718217,-73.998284 &key=AIzaSyCEXe5dDNptlIIvkxHQTc6ZeYms5mJDIHQ',
            title: 'Map'
        },
        {
            xtype: 'segmentedbutton',
            flex: 1,
            maxHeight: 50,
            width: 600,
            items: [
                {
                    style: 'background: ##5fa2dd',
                    text: 'Edit Data'
                },
                {
                    style: 'background: ##5fa2dd',
                    text: 'Save Records'
                },
                {
                    style: 'background: ##5fa2dd',
                    text: 'Map Imported Data'
                },
                {
                    style: 'background: ##5fa2dd',
                    text: 'Home'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            flex: 1,
            frame: true,
            margin: '48 0 32',
            width: 1300,
            title: 'Importname/Filename',
            titleAlign: 'center',
            store: 'RecordDataStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 170,
                    dataIndex: 'Name',
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    width: 190,
                    dataIndex: 'Address',
                    text: 'Address'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Address 2',
                    text: 'Address 2'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'City',
                    text: 'City'
                },
                {
                    xtype: 'gridcolumn',
                    width: 70,
                    dataIndex: 'State',
                    text: 'State'
                },
                {
                    xtype: 'gridcolumn',
                    width: 65,
                    dataIndex: 'Zip',
                    text: 'Zip'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Purpose',
                    text: 'Purpose'
                },
                {
                    xtype: 'gridcolumn',
                    width: 128,
                    dataIndex: 'Property Owner',
                    text: 'Property Owner'
                },
                {
                    xtype: 'gridcolumn',
                    width: 118,
                    dataIndex: 'Creation Date',
                    text: 'Creation Date'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Lat',
                    text: 'Lat'
                },
                {
                    xtype: 'gridcolumn',
                    width: 155,
                    dataIndex: 'Long',
                    text: 'Long'
                }
            ]
        }
    ]

});