/*
 * File: app/view/RecordViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StunningOctoPancake.view.RecordViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.recordviewport',

    requires: [
        'StunningOctoPancake.view.RecordViewportViewModel',
        'StunningOctoPancake.view.HeaderPanel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'recordviewport'
    },

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'headerpanel',
            flex: 1,
            margins: 'auto'
        },
        {
            xtype: 'gridpanel',
            flex: 1,
            frame: true,
            margin: '48 0 32',
            width: '85%',
            title: 'Importname/Filename',
            titleAlign: 'center',
            store: 'RecordDataStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'address',
                    text: 'Address'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'address_2',
                    text: 'Address 2'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'city',
                    text: 'City'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'state',
                    text: 'State'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'zip',
                    text: 'Zip'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'purpose',
                    text: 'Purpose'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'property_owner',
                    text: 'Property Owner'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'creation_date',
                    text: 'Creation Date'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'lat',
                    text: 'Lat'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'long',
                    text: 'Long'
                }
            ]
        }
    ]

});