/*
 * File: app/view/TabPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StunningOctoPancake.view.TabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.tabpanel',

    requires: [
        'StunningOctoPancake.view.TabPanelViewModel',
        'Ext.panel.Panel',
        'Ext.tab.Tab'
    ],

    viewModel: {
        type: 'tabpanel'
    },
    frame: true,
    margin: '48 0 32',
    maxHeight: 210,
    maxWidth: 832,
    minHeight: 210,
    minWidth: 382,
    width: '75%',
    bodyPadding: '64 32',
    activeTab: 0,

    items: [
        {
            xtype: 'panel',
            title: 'Upload CSV'
        },
        {
            xtype: 'panel',
            title: 'Search Records'
        }
    ]

});