/*
 * File: app/model/ImportRecords.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StunningOctoPancake.model.ImportRecords', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'name'
        },
        {
            name: 'address'
        },
        {
            name: 'address_2'
        },
        {
            name: 'city'
        },
        {
            name: 'state'
        },
        {
            name: 'zip'
        },
        {
            name: 'purpose'
        },
        {
            name: 'property_owner'
        },
        {
            name: 'creation_date'
        },
        {
            name: 'lat'
        },
        {
            name: 'long'
        }
    ]
});